### ISSUE TITLE
Paging a long list

### ISSUE THREAD

**Issue by waiandtgabriel** [svileng/ng-simplePagination#10]
Hi,

It might be a simple question but I am not sure if Is possible to add a (...) in the middle of the page numbers? I want to avoid my page numbers to be visualized in more than one line when I have a long list.

I've seen something like that,
```
<li ng-repeat="pageNumber in pages track by $index" ng-class="{ active : pagination.current == pageNumber, disabled : pageNumber == '...' }">
```
In another model (http://plnkr.co/edit/Wtkv71LIqUR4OhzhgpqL?p=preview) but so far ng-simplePagination is being great for me and I think I don't need to change.

Thanks!

**Comment by svileng** [comment]
Hey @waiandtgabriel — I don't think there is need to add that as a feature. You have the `$index` number from `ng-repeat`, so all you need to do is calculate the middle index, and add some `ng-if`s to decide whether to render a number, dots (...) or render nothing. Hope that helps.
