### ISSUE TITLE
Action Final Page

### ISSUE THREAD

**Issue by juanalemau** [svileng/ng-simplePagination#11]
I would like you to consider the action of the burden of the last page in your source code for example:

paginator.toFinalPage = function () {
         if (paginator.page! = null) {
           paginator.numPages paginator.page = -1;
         }
  };

Thank you for your contribution was very helpful to me.

**Comment by svileng** [comment]
@DoteroMauricio feel free to send a PR with your suggested changes for review. Thanks!
