### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by uderani** [svileng/ng-simplePagination#13]
i install it in bower components and my gulp serve is running, still when i try include it in the injector array in my app it gives me unknwon provider

where exactly should i include it

(function() {
    'use strict';

```
angular
    .module('airsole')
    .controller('FrontBlogController', FrontBlogController);

FrontBlogController.$inject = ['$http','$state', '$sce','$scope', 'AuthService', '$rootScope', 'Notify','$localStorage', '$filter', 'pagination'];

function FrontBlogController($http, $state, $sce, $scope, AuthService, $rootScope, Notify, $localStorage , $filter, pagination) {
```

**Comment by uderani** [comment]
I figured it out sir, thanks for your contribution! :) :+1:

**Comment by svileng** [comment]
Sorry for not replying earlier — good to hear you fixed it 👍🏻 Closing the issue.
