### ISSUE TITLE
Pagination not updating when data is filtered

### ISSUE THREAD

**Issue by sateesh2499** [svileng/ng-simplePagination#14]
The pagination is not updating when data is filtered. 
Is there any possibility to make it update according to the filtered items.
Thank you.

Please check the fiddle here: http://jsfiddle.net/gxt4nek9/

**Comment by svileng** [comment]
@sateesh2499 Your fiddle doesn't contain `ng-simplePagination` so I can't understand the problem you're trying to illustrate and how it relates to the library itself? Please provide a complete example showcasing the problem and describe the unexpected behaviour.

**Comment by sateesh2499** [comment]
My mistake. I didn't use the library. I just tried the fiddle provided in the credits section.

**Comment by svileng** [comment]
No worries — closing the issue.
