### ISSUE TITLE
limit pages shown?

### ISSUE THREAD

**Issue by qsys** [svileng/ng-simplePagination#7]
Just an idea: if you have many pages - this sometimes happens - and you want to limit the number of pages shown, something like below might be useful:

    paginationModule.filter('limitPages', function() {
      return function(input, paginator, total) {
        total = parseInt(total);
	    var first = 0;
     	    var last = Math.min(paginator.numPages, total);
	
   	    if (total < paginator.numPages) {		
		    var mid = total/2.0;
     		    if (paginator.page > paginator.numPages - mid) {
			    last = paginator.numPages
			    first = paginator.numPages-total
		     } else {
			     if (paginator.page+1 - mid > 0) {
				     first = paginator.page - Math.floor(mid);
				     last =  paginator.page + Math.ceil(mid);
			     }
		     }
	     }
         for (var i = first; i < last; i++) {
              input.push(i);
         }
         return input;
       };
     });

This can be used like ```ng-repeat = "n in [] | limitpages:pag:7"```

**Comment by svileng** [comment]
Sounds like a useful feature! Do you want to send a PR? @qsys

**Comment by qsys** [comment]
Y
​eah, sure, but not yet - I just want to ​check some things first, so not
to break anything. It might not be for right now, I'm leaving on holiday
pretty soon, for a few weeks. So, hopefully, by the end of july.

2015-06-28 12:44 GMT+02:00 Svilen Gospodinov <notifications@github.com>:

**Comment by svileng** [comment]
No probs, thanks a lot! I'm closing the issue.
