### ISSUE TITLE
Back-button browser, remember pagination 

### ISSUE THREAD

**Issue by Jaspur** [svileng/ng-simplePagination#8]
Hi,
When you go back via the browser button after a simplePaginated list it doesn't remember the page you were. Is there a way to remember the page you were? 

Like: list with 3 pages, clicked on second page, click item, go back in browser, open list on page 2.

**Comment by svileng** [comment]
Currently the plugin is not pushing to browser's history, so that functionality is not implemented at all. I think you can call `nextPage` and `prevPage` yourself in a controller/directive, and use https://github.com/rackt/history or https://github.com/browserstate/history.js to change the URL.
